// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numTrials  = Integer.parseInt(args[0]); 
		int counterL = 0;
		int counterH = 0 ;
		double ratio;
		
      for(int i = 0; i < numTrials; i++) {
		  double r = Math.random();
	    if (r < 0.5) {
			  counterL++;
		  } else {
			  counterH++;
		  }
		 
	 
		}
		 double Ratio = (double) counterL / (double) counterH;
	  System.out.println("Low count: " + counterL);
	  System.out.println("High count: " + counterH);
	  System.out.println("Ratio (low/High): " + Ratio);
	
	}
	}

	